package: redaxo_eingabekomponenten
version: '0.0.1-dev'
author: Benjamin Hacker
supportpage: https://github.com/BenJ1337/redaxo_eingabekomponenten

requires:
  php:
    version: '>=8.0.0'
  redaxo: '>=5.0.0'
